version: '3'
services:
  web:
    image: huetzin/magento2
    ports:
        - 80:80
    environment:
        - PHP_MEMORY_LIMIT=4G
        - PHP_DEFAULT_TIMEZONE=America/Mexico_City
        - SERVER_DOCROOT=/var/www/html
        - MAGENTO_USER=magento
    links:
        - db
    container_name: magento-web
    restart: always
  
  db:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
        - MYSQL_ROOT_PASSWORD=mysql
        - MYSQL_DATABASE=magento
    container_name: magento-db
    restart: always